In [2]:
import numpy as np

## Normalización de un vector

In [43]:
a = 2 - 1j
b = 3 + 4j

In [44]:
x = np.array([a,b])

In [48]:
def norma(vector):
    def coefLong(coef):
        return np.real(coef*np.conj(coef))
    def totalLong():
        sum = 0
        for i in vector:
            sum += coefLong(i)
        return sum**(1/2)
    totalSum = np.array(totalLong())
    #print(totalSum)
    return vector/totalSum

In [49]:
y = norma(x)

## Producto Interno y externo

In [51]:
def prodInter(A, B):
    return (B*np.matrix(A).getH())

In [53]:
prodInter(x, y)

matrix([[5.47722558+0.j]])

In [54]:
def prodExt(A, B):
    return np.transpose(np.matrix(A).getH()*B)

In [55]:
prodExt(x, y)

matrix([[0.91287093+0.j        , 0.36514837-2.00831604j],
        [0.36514837+2.00831604j, 4.56435465+0.j        ]])

## Ortogonalidad e indepedencia lineal 

In [74]:
matrix = np.array(
    [
        [0, 1 ,5 ,20],
        [3, 0, 4, 15],
        [0, 1, 9, 34],
        [1, 7, 0, 0]
    ])

In [26]:
A = np.array([1, 1j])
B = np.array([1j, 1])

In [62]:
def IndepLin(M):
    return (M.shape[1] == np.linalg.matrix_rank(M))

In [76]:
IndepLin(matrix)

True

In [77]:
def Orto(A, B):
    return (prodInter(A, B) == 0)

In [87]:
Orto(A, B)

matrix([[ True]])

## Producto tensorial

In [23]:
M = np.array(
    [
        [0, 1],
        [1, 0],
    ])

In [19]:
def M_Unit(M):
    return np.allclose(np.eye(np.shape(M)[0]), np.matrix(M).getH()*M)

np.eye(np.shape(M)[0]) Nos da un matriz identidad de 2X2  
np.matrix(M).getH()*M  Nos da $ M* M^\dagger $  
np.allclose(np.eye(np.shape(M)[0]), np.matrix(M).getH()*M) Nos da un booleano comparando las dos matrices

In [24]:
M_Unit(M)

True

In [28]:
np.kron(M, M) # Producto tensorial

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])